### ISSUE TITLE
learning task

### ISSUE THREAD

**Issue by keensam04** [keensam04/autohome#47]
**Tasks**
- [ ] read atleast chapter 1 of this [git ebook](https://git-scm.com/book/en/v2/Getting-Started-About-Version-Control)
- [ ] go through this [JSON tutorial](https://beginnersbook.com/2015/04/json-tutorial/). *Skip if you already know what json is*
- [ ] learn react from [this youtube playlist](https://www.youtube.com/playlist?list=PLC3y8-rFHvwgg3vaYJgHGnModB54rxOk3)
